repositories {
    mavenCentral()
}

dependencies {
    implementation project(":key.core")

    implementation 'com.google.code.gson:gson:2.10.1'

    implementation files('jmlparser/javaparser-core/target/jmlparser-core-3.25.10-b6-SNAPSHOT.jar')

    implementation files('jmlparser/javaparser-symbol-solver-core/target/jmlparser-symbol-solver-core-3.25.10-b6-SNAPSHOT.jar')
}